services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tap-tap-api
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://dimashulyachenko:1111@postgres:5432/dimashulyachenko?schema=public
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    container_name: postgres_tap
    environment:
      POSTGRES_USER: dimashulyachenko
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: dimashulyachenko
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
