-- AlterTable
ALTER TABLE "Carriage" ALTER COLUMN "estimated_income" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "income" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Footwear" ALTER COLUMN "estimated_income" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "income" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Helmet" ALTER COLUMN "estimated_income" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "income" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Pickaxe" ALTER COLUMN "estimated_income" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "income" SET DATA TYPE DOUBLE PRECISION;
